import { Box, Typography, Paper, Button } from "@mui/material";
import html2pdf from "html2pdf.js";

export default function ReportPreview({ content }) {
  if (!content) return null;

  const downloadPDF = () => {
    const element = document.getElementById("report-content");
    html2pdf()
      .from(element)
      .set({
        margin: 15,
        filename: "lab_analysis_report.pdf",
        html2canvas: { scale: 2 },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      })
      .save();
  };

  // 🔹 Define category display order
  const categoryOrder = [
    "Haematology",
    "Iron Status",
    "Renal Function & Metabolic",
    "Liver Function",
    "Lipids & Cardiovascular Risk",
    "Inflammatory Marker & CVD Risk",
    "Diabetes & Pancreatic",
    "Infectious Disease Serology",
    "Thyroid Function",
    "Tumour Markers",
    "Immunoserology",
    "Urinalysis",
    "Other",
  ];

  return (
    <Paper elevation={3} sx={{ mt: 4, p: 3 }}>
      <Typography variant="h6" gutterBottom>
        AI Analysis Report
      </Typography>

      <Box
        id="report-content"
        sx={{
          fontFamily: "Times New Roman, serif",
          color: "#000",
          lineHeight: 1.6,
          "& h2": { textAlign: "center", marginBottom: 2 },
          "& h3": { marginTop: 2, marginBottom: 1 },
          "& p, & li": { fontSize: "13px" },
        }}
      >
        <h2>Medical Laboratory Analysis Report</h2>

        {/* Patient Info */}
        <h3>Patient Information</h3>
        <p>
          <b>Name:</b> {content.patient?.name || "Not specified"}
        </p>
        <p>
          <b>Age:</b> {content.patient?.age || "Not specified"}
        </p>
        <p>
          <b>Sex:</b> {content.patient?.sex || "Not specified"}
        </p>
        <p>
          <b>Date:</b> {content.patient?.date || "Not specified"}
        </p>

        {/* Categories */}
        <h3>Detailed Lab Results</h3>
        {categoryOrder.map((cat) => {
          const section = content.categories?.[cat];
          if (!section || (Array.isArray(section) && section.length === 0)) {
            return null; // skip empty categories
          }

          return (
            <div key={cat} style={{ marginBottom: "10px" }}>
              <h4 style={{ marginBottom: "4px", color: "#222" }}>{cat}</h4>

              {/* Special case: Urinalysis might be an object */}
              {cat === "Urinalysis" &&
              typeof section === "object" &&
              !Array.isArray(section) ? (
                <ul>
                  <li>
                    <b>Appearance:</b> {section.Appearance || "Not provided"}
                  </li>
                  <li>
                    <b>Urine Chemical:</b>{" "}
                    {section["Urine Chemical"] || "Not provided"}
                  </li>
                  <li>
                    <b>Microscopic:</b> {section.Microscopic || "Not provided"}
                  </li>
                </ul>
              ) : (
                <ul>
                  {section.map((t, idx) => (
                    <li key={idx}>
                      <b>{t.test}</b>: {t.result}
                      {t.reference_range && t.reference_range !== "Not provided"
                        ? ` (Ref: ${t.reference_range})`
                        : ""}
                      <br />
                      <i>{t.interpretation || ""}</i>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          );
        })}

        {/* Abnormal findings */}
        <h3>Abnormal Findings</h3>
        {content.abnormal_findings?.length > 0 ? (
          <ul>
            {content.abnormal_findings.map((f, idx) => (
              <li key={idx}>
                <b>{f.test}</b>: {f.result}
                {f.reference_range && f.reference_range !== "Not provided"
                  ? ` (Ref: ${f.reference_range})`
                  : ""}
                <br />
                <i>{f.note}</i>
              </li>
            ))}
          </ul>
        ) : (
          <p>No abnormal findings detected.</p>
        )}

        {/* Summary */}
        <h3>Summary</h3>
        <p>{content.summary || "Not specified"}</p>

        {/* Recommendations */}
        <h3>Recommendations</h3>
        <p>{content.recommendations || "Not specified"}</p>

        {/* Follow-up */}
        <h3>Follow-up</h3>
        <p>{content.follow_up || "Not specified"}</p>

        <div
          style={{
            marginTop: "40px",
            fontSize: "11px",
            textAlign: "center",
            color: "#444",
          }}
        >
          <hr />
          <p>
            Generated by AI Assistant – For clinical support only, not a
            substitute for physician judgment.
          </p>
        </div>
      </Box>

      <Button variant="contained" sx={{ mt: 2 }} onClick={downloadPDF}>
        Download PDF
      </Button>
    </Paper>
  );
}
