import { Box, Typography, Paper, Button } from "@mui/material";
import html2pdf from "html2pdf.js";

export default function ReportPreview({ content }) {
  if (!content) return null;

  const downloadPDF = () => {
    const element = document.getElementById("report-content");
    html2pdf()
      .from(element)
      .set({
        margin: 10,
        filename: "lab_analysis_report.pdf",
        html2canvas: { scale: 2 },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      })
      .save();
  };

  return (
    <Paper elevation={3} sx={{ mt: 4, p: 3 }}>
      <Typography variant="h6" gutterBottom>
        AI Analysis Report
      </Typography>

      <Box
        id="report-content"
        sx={{
          fontFamily: "Times New Roman, serif",
          color: "#000",
          lineHeight: 1.5,
          "& h2": { textAlign: "center", marginBottom: 2 },
          "& h3": { marginTop: 2, marginBottom: 1 },
          "& p, & li": { fontSize: "14px" },
        }}
      >
        <h2>Medical Laboratory Analysis Report</h2>

        <h3>Patient Information</h3>
        <p>
          <b>Name:</b> {content.patient?.name}
        </p>
        <p>
          <b>Age:</b> {content.patient?.age}
        </p>
        <p>
          <b>Sex:</b> {content.patient?.sex}
        </p>
        <p>
          <b>Date:</b> {content.patient?.date}
        </p>

        <h3>Abnormal Findings</h3>
        {content.abnormal_findings?.length ? (
          <ul>
            {content.abnormal_findings.map((f, idx) => (
              <li key={idx}>
                <b>{f.test}</b>: {f.result} (Ref: {f.reference_range})<br />
                <i>{f.note}</i>
              </li>
            ))}
          </ul>
        ) : (
          <p>No abnormal findings detected.</p>
        )}

        <h3>Summary</h3>
        <p>{content.summary}</p>

        <h3>Recommendations</h3>
        <p>{content.recommendations}</p>

        <h3>Follow-up</h3>
        <p>{content.follow_up}</p>

        <div
          style={{
            marginTop: "40px",
            fontSize: "12px",
            textAlign: "center",
          }}
        >
          <hr />
          <p>
            Generated by AI Assistant – For clinical support only, not a
            substitute for physician judgment.
          </p>
        </div>
      </Box>

      <Button variant="contained" sx={{ mt: 2 }} onClick={downloadPDF}>
        Download PDF
      </Button>
    </Paper>
  );
}
